---
title: Wyzant Prod CMS
timezone: America/Chicago
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    author: 
- scope:
    path: ''
    type: posts
  values:
    permalink: blog/:title/
    layout: post
    author: 
    profile-image: 
email: your-email@domain.com
sass:
  sass_dir: styles/
  style: compressed
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: https://www.wyzant.com
markdown: kramdown
