---
title: Wyzant Blog Name
timezone: America/Chicago
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/blog/uploads/:path/"
  blog:
    title: blog
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    job-title: 
    bio: 
    profile-image: 
    author: Wyzant
    meta-title: 
    meta-description:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    meta-title: 
    author: Wyzant
    sub-headline: 
    hero-image: 
    meta-description:
    post-description: 
meta-title: Title here
gems:
- octopress-paginate
- jekyll/tagging
tag_page_layout: tag-page
tag_page_dir: blog/tag
tag_permalink_style: pretty
pagination:
  limit: false
  per_page: 4
sub-headline: Sub headline goes here
hero-image: "/blog/uploads/homepage-hero-default.png"
meta-description: slkdfjlsfksklfkskldfjlks
email: your-email@domain.com
sass:
  sass_dir: blog/styles
  style: compressed
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
banner-background-image: "/blog/uploads/banner-background-default.png"
banner-headline: Ready To Get Started?
banner-sub-headline: Start Your Tutor Search Today.
banner-cta-text: Get Started
banner-cta-url: "/match"
baseurl: 
url: https://www.wyzant.com
markdown: kramdown
