---
title: Wyzant Blog Name
timezone: America/Chicago
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/authors/:title/"
    layout: author
    job-title: 
    bio: 
    profile-image: 
    author: A Wyzant Staff Member
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    page-title: 
    author: A Wyzant Staff Member
    sub-headline: 
    hero-image: 
    description: 
page-title: Title here
gems:
- octopress-paginate
pagination:
  limit: false
  per_page: 4
sub-headline: Sub headline goes here
hero-image: 
email: your-email@domain.com
sass:
  sass_dir: styles/
  style: compressed
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
banner-background-image: "/uploads/banner-background-default.png"
banner-headline: "Ready To Get Started?"
banner-sub-headline: "Start Your Tutor Search Today."
banner-cta-text: "Get Started"
banner-cta-url: "#"
baseurl: 
url: https://www.wyzant.com
markdown: kramdown
