---
title: The Wyzant Blog
timezone: America/Chicago
collections:
  authors:
    title: Authors
    output: true
  tutor-tags:
    title: Tutor Tags
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/blog/uploads/:path/"
  blog:
    title: blog
    output: true
  tutorPosts:
    title: Tutor Posts
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    job-title:
    bio:
    profile-image:
    author: Wyzant
    meta-title:
    meta-description:
- scope:
    path: ''
    type: tutor-tags
  values:
    title:
    permalink: "/blog/tutor/tag/:title/"
    layout: tutor-tag-page
    meta-description:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    meta-title:
    author: Wyzant
    sub-headline:
    hero-image:
    meta-description:
    post-description:
- scope:
    path: ''
    type: tutorPosts
  values:
    permalink: "/blog/tutor/:title/"
    layout: post
    meta-title:
    author: Wyzant
    sub-headline:
    hero-image:
    meta-description:
    post-description:
meta-title: The Wyzant Blog
gems:
- octopress-paginate
- jekyll/tagging
tag_page_layout: tag-page
tag_page_dir: blog/tag
tag_permalink_style: pretty
sub-headline: What will you learn?
hero-image: "/blog/uploads/homepage-hero-default.png"
meta-description: Learning is the essence of Wyzant. We’re hungry for the next fun
  fact, deep dive and discovery session. We love to learn, and in browsing these pages,
  we hope you will too.
email: your-email@domain.com
sass:
  sass_dir: blog/styles
  style: compressed
description: Learning is the essence of Wyzant. We’re hungry for the next fun fact,
  deep dive and discovery session. We love to learn, and in browsing these pages,
  we hope you will too.
banner-background-image: "/blog/uploads/banner-background-default.png"
banner-headline: Ready To Get Started?
banner-sub-headline: Start Your Tutor Search Today.
banner-cta-text: Get Started
banner-cta-url: "/match"
baseurl:
url: https://www.wyzant.com
markdown: kramdown
